/* Automatically generated by './build/build-components-entry.js' */

import { default as MazArrowIcon } from './MazArrowIcon.vue'
import { default as MazAvatar } from './MazAvatar.vue'
import { default as MazBackDrop } from './MazBackDrop.vue'
import { default as MazBadge } from './MazBadge.vue'
import { default as MazBottomSheet } from './MazBottomSheet.vue'
import { default as MazBtn } from './MazBtn.vue'
import { default as MazCard } from './MazCard.vue'
import { default as MazCarousel } from './MazCarousel.vue'
import { default as MazChart } from './MazChart.vue'
import { default as MazCheckbox } from './MazCheckbox.vue'
import { default as MazDialog } from './MazDialog.vue'
import { default as MazDialogPromise } from './MazDialogPromise.vue'
import { default as MazDrawer } from './MazDrawer.vue'
import { default as MazDropzone } from './MazDropzone.vue'
import { default as MazGallery } from './MazGallery.vue'
import { default as MazIcon } from './MazIcon.vue'
import { default as MazInput } from './MazInput.vue'
import { default as MazInputNumber } from './MazInputNumber.vue'
import { default as MazInputPrice } from './MazInputPrice.vue'
import { default as MazInputTags } from './MazInputTags.vue'
import { default as MazLazyImg } from './MazLazyImg.vue'
import { default as MazPhoneNumberInput } from './MazPhoneNumberInput.vue'
import { default as MazPicker } from './MazPicker.vue'
import { default as MazRadioButtons } from './MazRadioButtons.vue'
import { default as MazSelect } from './MazSelect.vue'
import { default as MazSlider } from './MazSlider.vue'
import { default as MazSpinner } from './MazSpinner.vue'
import { default as MazSwitch } from './MazSwitch.vue'
import { default as MazTabsBar } from './MazTabsBar.vue'
import { default as MazTabsWrapper } from './MazTabsWrapper.vue'
import { default as MazTabsContent } from './MazTabsContent.vue'
import { default as MazTransitionExpand } from './MazTransitionExpand.vue'

export {
  MazArrowIcon,
  MazAvatar,
  MazBackDrop,
  MazBadge,
  MazBottomSheet,
  MazBtn,
  MazCard,
  MazCarousel,
  MazChart,
  MazCheckbox,
  MazDialog,
  MazDialogPromise,
  MazDrawer,
  MazDropzone,
  MazGallery,
  MazIcon,
  MazInput,
  MazInputNumber,
  MazInputPrice,
  MazInputTags,
  MazLazyImg,
  MazPhoneNumberInput,
  MazPicker,
  MazRadioButtons,
  MazSelect,
  MazSlider,
  MazSpinner,
  MazSwitch,
  MazTabsBar,
  MazTabsWrapper,
  MazTabsContent,
  MazTransitionExpand,
}

export default {
  MazArrowIcon,
  MazAvatar,
  MazBackDrop,
  MazBadge,
  MazBottomSheet,
  MazBtn,
  MazCard,
  MazCarousel,
  MazChart,
  MazCheckbox,
  MazDialog,
  MazDialogPromise,
  MazDrawer,
  MazDropzone,
  MazGallery,
  MazIcon,
  MazInput,
  MazInputNumber,
  MazInputPrice,
  MazInputTags,
  MazLazyImg,
  MazPhoneNumberInput,
  MazPicker,
  MazRadioButtons,
  MazSelect,
  MazSlider,
  MazSpinner,
  MazSwitch,
  MazTabsBar,
  MazTabsWrapper,
  MazTabsContent,
  MazTransitionExpand,
}
