---
version: '2'
plugins:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - typescript
  eslint:
    enabled: false
    channel: eslint-9
  fixme:
    enabled: true
  stylelint:
    enabled: false

checks:
  method-complexity:
    enabled: true
    config:
      threshold: 15

exclude_patterns:
  - .husky/
  - .vscode/
  - '**/tests/'
  - '**/spec/'
  - '**/*.d.ts'
  - node_modules/*
  - packages/lib/tests/*
  - packages/lib/build/*
