import type { UserConfig } from '@commitlint/types'

export default <UserConfig> {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'perf',
        'refactor',
        'test',
        'docs',
        'style',
        'chore',
        'clean',
        'ci',
        'revert',
        'build',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'docs',
        'release',
        'deps',
        'nuxt-app',
        'vue-app',
        'cli',
        'maz-ui',
        '@maz-ui/nuxt',
        '@maz-ui/icons',
        '@maz-ui/cli',
        '@maz-ui/eslint-config',
        '@maz-ui/themes',
        '@maz-ui/translations',
        '@maz-ui/utils',
        '@maz-ui/node',
        '@maz-ui/mcp',
        '@maz-ui/vite-config',
      ],
    ],
    'subject-case': [2, 'never', ['upper-case', 'pascal-case', 'start-case']],
    'header-max-length': [2, 'always', 200],
  },
}
