minimumReleaseAgeExclude:
  - '@yoloship/*'
  - '@maz-ui/node@5.0.0-beta.26'
  - '@maz-ui/utils@5.0.0-beta.25'
  - relizy*

shellEmulator: true

# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: warn-downgrade

packages:
  - apps/*
  - packages/*
  - tools/*
  - .

onlyBuiltDependencies:
  - '@swc/core'
  - nx
  - unrs-resolver
  - esbuild
  - vue-demi

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  nx: true
  sharp: false
  vue-demi: true
