shellEmulator: true
# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: warn-downgrade

packages:
  - apps/*
  - packages/*
  - tools/*
  - .

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - nx
  - unrs-resolver
  - vue-demi
