packages:
  - 'apps/*'
  - 'packages/*'
  - '.'

catalog:
  '@babel/core': ^7.27.4
  '@babel/preset-env': ^7.27.2
  '@babel/preset-typescript': ^7.27.1
  '@eslint/markdown': ^6.4.0
  '@nuxt/kit': ^3.17.4
  '@nuxt/schema': ^3.17.4
  '@types/google.maps': ^3.58.1
  '@vitejs/plugin-vue': ^5.2.4
  '@vitest/coverage-v8': ^3.2.0
  '@vue/compiler-sfc': ^3.5.16
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.7.0
  autoprefixer: ^10.4.21
  c8: ^10.1.3
  chalk: 5.4.1
  chart.js: ^4.4.9
  dayjs: ^1.11.13
  defu: ^6.1.4
  dropzone: ^5.9.3
  eslint-plugin-vuejs-accessibility: ^2.4.1
  fs: 0.0.2
  glob: ^11.0.2
  jsdom: ^26.1.0
  json-templater: ^1.2.0
  libphonenumber-js: ^1.12.8
  minimist: ^1.2.8
  nuxt: ^3.17.4
  onchange: ^7.1.0
  path: ^0.12.7
  postcss: ^8.5.4
  postcss-html: ^1.8.0
  postcss-import: ^16.1.0
  postcss-nested: ^7.0.2
  postcss-replace: ^2.0.1
  postcss-simple-vars: ^7.0.1
  postcss-url: ^10.1.3
  rimraf: ^6.0.1
  sass: ^1.89.1
  semver: ^7.7.2
  sirv: ^3.0.1
  stylelint: ^16.20.0
  stylelint-config-recommended-vue: ^1.6.0
  stylelint-config-standard: ^38.0.0
  stylelint-config-standard-scss: ^15.0.1
  stylelint-config-tailwindcss: ^1.0.0
  stylelint-scss: ^6.12.0
  tailwindcss: ^3.4.17
  typescript: ~5.8.3
  unplugin-auto-import: ^19.3.0
  unplugin-vue-components: ^28.7.0
  valibot: ^1.1.0
  vite: ^6.3.5
  vite-plugin-css-injected-by-js: ^3.5.2
  vite-plugin-dts: ^4.5.4
  vite-plugin-lib-inject-css: ^2.2.2
  vite-plugin-static-copy: ^3.0.0
  vite-svg-loader: ^5.1.0
  vitest: ^3.2.0
  vitest-canvas-mock: ^0.3.3
  vue: ^3.5.16
  vue-chartjs: ^5.3.2
  vue-loader: ^17.4.2
  vue-router: ^4.5.1
  vue-tsc: ^2.2.10
