blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://maz-ui.com/
    about: Check the official documentation before opening an issue
  - name: 💬 Discussions
    url: https://github.com/LouisMazel/maz-ui/discussions
    about: Ask questions and discuss with the community
