export const baseColors = {
  transparent: 'transparent',
  black: 'var(--maz-color-black)',
  'black-contrast': 'var(--maz-color-black-contrast)',
  white: 'var(--maz-color-white)',
  'white-contrast': 'var(--maz-color-white-contrast)',
  current: 'currentColor',
  normal: 'var(--maz-color-text)',
  color: 'var(--maz-color-bg)',
  'color-light': 'var(--maz-color-bg-light)',
  'color-lighter': 'var(--maz-color-bg-lighter)',
  theme: 'var(--maz-color-bg-theme)',
  'theme-hover': 'var(--maz-color-bg-theme-hover)',
  'bg-dark': 'var(--maz-bg-color-dark)',
  'bg-light': 'var(--maz-bg-color-light)',
  light: 'var(--maz-color-text-light)',
  dark: 'var(--maz-color-text-dark)',
  muted: 'var(--maz-color-muted)',
  overlay: 'var(--maz-bg-overlay)',
}

export const variations = [
  'DEFAULT',
  '50',
  '100',
  '200',
  '300',
  '400',
  '600',
  '700',
  '800',
  '900',
  'contrast',
  'alpha',
  'alpha-20',
  'alpha-10',
  'alpha-05',
]

export const variatingColors = {
  primary: true,
  secondary: true,
  info: true,
  success: true,
  warning: true,
  danger: true,
}
