/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MazAnimatedCounter: typeof import('maz-ui/components/MazAnimatedCounter')['default']
    MazBadge: typeof import('maz-ui/components/MazBadge')['default']
    MazBtn: typeof import('maz-ui/components/MazBtn')['default']
    MazCard: typeof import('maz-ui/components/MazCard')['default']
    MazChart: typeof import('maz-ui/components/MazChart')['default']
    MazCheckbox: typeof import('maz-ui/components/MazCheckbox')['default']
    MazChecklist: typeof import('maz-ui/components/MazChecklist')['default']
    MazChevronUp: typeof import('@maz-ui/icons')['MazChevronUp']
    MazCircularProgressBar: typeof import('maz-ui/components/MazCircularProgressBar')['default']
    MazCodeBracket: typeof import('@maz-ui/icons')['MazCodeBracket']
    MazExpandAnimation: typeof import('maz-ui/components/MazExpandAnimation')['default']
    MazGallery: typeof import('maz-ui/components/MazGallery')['default']
    MazIcon: typeof import('maz-ui/components/MazIcon')['default']
    MazInput: typeof import('maz-ui/components/MazInput')['default']
    MazInputCode: typeof import('maz-ui/components/MazInputCode')['default']
    MazInputNumber: typeof import('maz-ui/components/MazInputNumber')['default']
    MazInputPrice: typeof import('maz-ui/components/MazInputPrice')['default']
    MazLink: typeof import('maz-ui/components/MazLink')['default']
    MazPicker: typeof import('maz-ui/components/MazPicker')['default']
    MazSelect: typeof import('maz-ui/components/MazSelect')['default']
    MazSlider: typeof import('maz-ui/components/MazSlider')['default']
    MazStepper: typeof import('maz-ui/components/MazStepper')['default']
    MazTable: typeof import('maz-ui/components/MazTable')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
