/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MazCard: typeof import('maz-ui/components/MazCard')['default']
    MazChevronUp: typeof import('@maz-ui/icons')['MazChevronUp']
    MazCodeBracket: typeof import('@maz-ui/icons')['MazCodeBracket']
    MazExpandAnimation: typeof import('maz-ui/components/MazExpandAnimation')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
