/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AcademicCap: typeof import('@maz-ui/icons')['AcademicCap']
    MazBtn: typeof import('maz-ui/components/MazBtn')['default']
    MazLink: typeof import('maz-ui/components/MazLink')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vClickOutside: typeof import('maz-ui/directives')['vClickOutside']
  }
}
