/* eslint-disable max-len */
export default {
  // Form components
  'maz-btn': 'MazBtn is a stand-alone component replaces the standard html button with a beautiful design system. Many options like colors, sizes, disabled state, loading state, includes icons. Support of router-link and nuxt-link',
  'maz-btn-group': 'MazBtn is a stand-alone component. It\'s a group of buttons with a beautiful design system. It helps the user to choose an option.',
  'maz-card': 'MazCard is a stand-alone component to display some texts, images and you can add buttons actions',
  'maz-carousel': 'MazCarousel is a stand-alone component to display and manage items in a row',
  'maz-checkbox': 'MazCheckbox is a stand-alone component replaces the standard html input checkbox. Color option available',
  'maz-dropzone': 'MazDropzone is a stand-alone component to help user upload different type of files with a beautiful design system. It works with dropzone.js and is not SSR compatible with Nuxt.JS',
  'maz-input': 'MazInput is a stand-alone component replaces the standard html input text or textarea with a beautiful design system. Many options like colors, sizes, disabled, loading, error, warning, valid states, error messages, includes icons.',
  'maz-input-tags': 'MazInputTags is a stand-alone component like free inputs to help user select many values and return an Array of strings, color option available.',
  'maz-picker': 'MazPicker is a stand-alone component for select dates and time. Use range, date and time mode',
  'maz-phone-number-input': 'MazPhoneNumberInput is a standalone input component to help the user enter a phone number and validate it according to the country',
  'maz-radio': 'MazRadio is a stand-alone component replaces the standard html input radio. Color option available',
  'maz-search': 'MazSearch is a stand-alone component input. Text field to interface user searches on an API. The value entered is returned with a debounce (no event if the user continues to type). Give the results to the component and it displays it in a dropdown list (custom templates options available)',
  'maz-select': 'MazSelect is a stand-alone component replaces the standard html input select with a beautiful design system. Many options like multiple values, search text field, custom templates options, colors, sizes, disabled, loading, error, warning, valid states, error messages, includes icons.',
  'maz-slider': 'MazSlider is a stand-alone component replaces the standard html input range with a beautiful design system. Many options like multiple cursors and values, colors, sizes and logarithmic/exponential values',
  'maz-switch': 'MazSwitch is a stand-alone component. It\'s like checkbox with a different design. colors options available.',
  // UI components
  'maz-avatar': 'MazAvatar is a stand-alone component. Typically used to display circular or square user profile pictures. This component will allow you to dynamically size, border and shadow. Can become a link if you give a URL. Editable option will show a button with blur effect and return an event on click',
  'maz-bottom-sheet': 'MazBottom is a stand-alone component like a simple dialog but at the bottom of screen',
  'maz-collapse': 'MazCollapse is a stand-alone component to show or hide content with animation with click or programmatically',
  'maz-dialog': 'MazDialog is a stand-alone dialog component to show important informations to the user or propose specific action. Many options available: You can hide the header or the footer, full-size layout, differents states etc.',
  'maz-draggable-list': 'MazDraggableList is a stand-alone component to display a list and allow reorder items by dragg and drop. Works with vuedraggable. Custom item template available, see examples',
  'maz-dropdown': 'MazDropdown is a stand-alone component to show a list on click or on hover.',
  'maz-flex': 'MazFlex is a stand-alone component. It\'s a container to manage flexbox CSS properties',
  'maz-gallery': 'MazGallery is a stand-alone component. It\'s a container to show images',
  'maz-img': 'MazImg is a stand-alone component to display image with some options with a full size preview on click. Fully responsive !',
  'maz-list': 'MazList is a stand-alone component to display a simple list. No-scroll, no-shadow and transition options available.',
  'maz-loader': 'MazLoader is a stand-alone component to display a simple loader. Color option available soon.',
  'maz-pagination': 'MazPagination is a stand-alone component to handle the pagination of items API or pages.',
  'maz-plotly': 'MazPloty is a stand-alone component to display Plotly.JS graphics. It\'s a wrapper not SSR compatible with Nuxt.JS',
  'maz-progress-bar': 'MazProgressBar is a stand-alone component to display a simple animated progress bar. Size and colors options available',
  'maz-read-more': 'MazReadMore is a stand-alone component to display a simple a part of text with a link to show all the content. Translation, truncate length and text class options available.',
  'maz-sidebar': 'MazSidebar is a stand-alone component to display a right or left panel with animation. Propose content or navigation menu to the user. Loading option will showing a loader on the panel. Can open over the content with absolute option and some other options',
  'maz-spinner': 'MazSpinner is a stand-alone component to a SVG loader with animation. Color and size options',
}
/* eslint-enable max-len */