
/* Automatically generated by './build/bin/build-entry.js (thanks element-ui)' */
/* eslint-disable */

import MazBtn from '../packages/components/MazBtn/index.js'
import MazBtnGroup from '../packages/components/MazBtnGroup/index.js'
import MazCheckbox from '../packages/components/MazCheckbox/index.js'
import MazCollapse from '../packages/components/MazCollapse/index.js'
import MazDialog from '../packages/components/MazDialog/index.js'
import MazDraggableList from '../packages/components/MazDraggableList/index.js'
import MazDropzone from '../packages/components/MazDropzone/index.js'
import MazFlex from '../packages/components/MazFlex/index.js'
import MazInput from '../packages/components/MazInput/index.js'
import MazInputTags from '../packages/components/MazInputTags/index.js'
import MazLoader from '../packages/components/MazLoader/index.js'
import MazPagination from '../packages/components/MazPagination/index.js'
import MazPhoneNumberInput from '../packages/components/MazPhoneNumberInput/index.js'
import MazReadMore from '../packages/components/MazReadMore/index.js'
import MazResponsiveMenu from '../packages/components/MazResponsiveMenu/index.js'
import MazSearch from '../packages/components/MazSearch/index.js'
import MazSelect from '../packages/components/MazSelect/index.js'
import MazSidebar from '../packages/components/MazSidebar/index.js'
import MazSpinner from '../packages/components/MazSpinner/index.js'
import MazSwitch from '../packages/components/MazSwitch/index.js'
import MazTabsBar from '../packages/components/MazTabsLayout/MazTabsBar/index.js'
import MazTabsContent from '../packages/components/MazTabsLayout/MazTabsContent/index.js'
import MazTabsContentItem from '../packages/components/MazTabsLayout/MazTabsContentItem/index.js'
import MazTransitionExpand from '../packages/components/MazTransitionExpand/index.js'
import { version } from '../package.json'

const components = [
  MazBtn,
  MazBtnGroup,
  MazCheckbox,
  MazCollapse,
  MazDialog,
  MazDraggableList,
  MazDropzone,
  MazFlex,
  MazInput,
  MazInputTags,
  MazLoader,
  MazPagination,
  MazPhoneNumberInput,
  MazReadMore,
  MazResponsiveMenu,
  MazSearch,
  MazSelect,
  MazSidebar,
  MazSpinner,
  MazSwitch,
  MazTabsBar,
  MazTabsContent,
  MazTabsContentItem,
  MazTransitionExpand,
]

const install = (Vue, opts = {}) => {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version,
  install,
  MazBtn,
  MazBtnGroup,
  MazCheckbox,
  MazCollapse,
  MazDialog,
  MazDraggableList,
  MazDropzone,
  MazFlex,
  MazInput,
  MazInputTags,
  MazLoader,
  MazPagination,
  MazPhoneNumberInput,
  MazReadMore,
  MazResponsiveMenu,
  MazSearch,
  MazSelect,
  MazSidebar,
  MazSpinner,
  MazSwitch,
  MazTabsBar,
  MazTabsContent,
  MazTabsContentItem,
  MazTransitionExpand
}

export {
  version,
  install
}
/* eslint-enable */
