/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MazBtn {
        "block": boolean;
        "color": 'primary' | 'secondary' | 'info' | 'success' | 'warning' | 'danger' | 'white' | 'black' | 'transparent' | 'theme';
        "contentClass"?: string;
        "disabled": boolean;
        "fab": boolean;
        "icon"?: string;
        "leftIcon"?: string;
        "loading": boolean;
        "noElevation": boolean;
        "noLeading": boolean;
        "noPadding": boolean;
        "noRounded": boolean;
        "noUnderline": boolean;
        "outline": boolean;
        "pastel": boolean;
        "rightIcon"?: string;
        "rounded": boolean;
        "size": 'xl' | 'lg' | 'md' | 'sm' | 'xs' | 'mini';
        "type": 'submit' | 'reset' | 'button';
        "variant": 'button' | 'link';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLMazBtnElement extends Components.MazBtn, HTMLStencilElement {
    }
    var HTMLMazBtnElement: {
        prototype: HTMLMazBtnElement;
        new (): HTMLMazBtnElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "maz-btn": HTMLMazBtnElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MazBtn {
        "block"?: boolean;
        "color"?: 'primary' | 'secondary' | 'info' | 'success' | 'warning' | 'danger' | 'white' | 'black' | 'transparent' | 'theme';
        "contentClass"?: string;
        "disabled"?: boolean;
        "fab"?: boolean;
        "icon"?: string;
        "leftIcon"?: string;
        "loading"?: boolean;
        "noElevation"?: boolean;
        "noLeading"?: boolean;
        "noPadding"?: boolean;
        "noRounded"?: boolean;
        "noUnderline"?: boolean;
        "outline"?: boolean;
        "pastel"?: boolean;
        "rightIcon"?: string;
        "rounded"?: boolean;
        "size"?: 'xl' | 'lg' | 'md' | 'sm' | 'xs' | 'mini';
        "type"?: 'submit' | 'reset' | 'button';
        "variant"?: 'button' | 'link';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "maz-btn": MazBtn;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "maz-btn": LocalJSX.MazBtn & JSXBase.HTMLAttributes<HTMLMazBtnElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
