#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# branch="$(git rev-parse --abbrev-ref HEAD)"

# if [ "$branch" = "master" ]; then
#   echo "You can't commit directly to master branch"
#   exit 1
# fi

make lint-staged
make lint-staged-lib
make lint-staged-testing
make lint-staged-cli
