
/* Automatically generated by './build/build-entries.js (thanks element-ui)' */
/* eslint-disable */

import MazDropzone from './components/MazDropzone/index.js'
import MazPlotly from './components/MazPlotly/index.js'
import { version } from './../package.json'

const components = [
  MazDropzone,
  MazPlotly,
]

const install = (Vue, opts = {}) => {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version,
  install,
  MazDropzone,
  MazPlotly
}

export {
  version,
  install
}
/* eslint-enable */
