
/* Automatically generated by './build/build-entries.js (thanks element-ui)' */
/* eslint-disable */

import MazAvatar from './components/MazAvatar/index.js'
import MazBottomSheet from './components/MazBottomSheet/index.js'
import MazBtn from './components/MazBtn/index.js'
import MazBtnGroup from './components/MazBtnGroup/index.js'
import MazCheckbox from './components/MazCheckbox/index.js'
import MazCollapse from './components/MazCollapse/index.js'
import MazDialog from './components/MazDialog/index.js'
import MazDraggableList from './components/MazDraggableList/index.js'
import MazDropdown from './components/MazDropdown/index.js'
import MazDropzone from './components/MazDropzone/index.js'
import MazFlex from './components/MazFlex/index.js'
import MazGallery from './components/MazGallery/index.js'
import MazImg from './components/MazImg/index.js'
import MazInput from './components/MazInput/index.js'
import MazInputTags from './components/MazInputTags/index.js'
import MazList from './components/MazList/index.js'
import MazListItem from './components/MazList/MazListItem/index.js'
import MazLoader from './components/MazLoader/index.js'
import MazPagination from './components/MazPagination/index.js'
import MazPicker from './components/MazPicker/index.js'
import MazPlotly from './components/MazPlotly/index.js'
import MazProgressBar from './components/MazProgressBar/index.js'
import MazPhoneNumberInput from './components/MazPhoneNumberInput/index.js'
import MazRadio from './components/MazRadio/index.js'
import MazReadMore from './components/MazReadMore/index.js'
import MazResponsiveMenu from './components/MazResponsiveMenu/index.js'
import MazSearch from './components/MazSearch/index.js'
import MazSelect from './components/MazSelect/index.js'
import MazSidebar from './components/MazSidebar/index.js'
import MazSlider from './components/MazSlider/index.js'
import MazSpinner from './components/MazSpinner/index.js'
import MazStepper from './components/MazStepper/index.js'
import MazSwitch from './components/MazSwitch/index.js'
import MazTabsBar from './components/MazTabsLayout/MazTabsBar/index.js'
import MazTabsContent from './components/MazTabsLayout/MazTabsContent/index.js'
import MazTabsContentItem from './components/MazTabsLayout/MazTabsContentItem/index.js'
import MazTransitionExpand from './components/MazTransitionExpand/index.js'
import { version } from './../package.json'

const components = [
  MazAvatar,
  MazBottomSheet,
  MazBtn,
  MazBtnGroup,
  MazCheckbox,
  MazCollapse,
  MazDialog,
  MazDraggableList,
  MazDropdown,
  MazDropzone,
  MazFlex,
  MazGallery,
  MazImg,
  MazInput,
  MazInputTags,
  MazList,
  MazListItem,
  MazLoader,
  MazPagination,
  MazPicker,
  MazPlotly,
  MazProgressBar,
  MazPhoneNumberInput,
  MazRadio,
  MazReadMore,
  MazResponsiveMenu,
  MazSearch,
  MazSelect,
  MazSidebar,
  MazSlider,
  MazSpinner,
  MazStepper,
  MazSwitch,
  MazTabsBar,
  MazTabsContent,
  MazTabsContentItem,
  MazTransitionExpand,
]

const install = (Vue, opts = {}) => {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version,
  install,
  MazAvatar,
  MazBottomSheet,
  MazBtn,
  MazBtnGroup,
  MazCheckbox,
  MazCollapse,
  MazDialog,
  MazDraggableList,
  MazDropdown,
  MazDropzone,
  MazFlex,
  MazGallery,
  MazImg,
  MazInput,
  MazInputTags,
  MazList,
  MazListItem,
  MazLoader,
  MazPagination,
  MazPicker,
  MazPlotly,
  MazProgressBar,
  MazPhoneNumberInput,
  MazRadio,
  MazReadMore,
  MazResponsiveMenu,
  MazSearch,
  MazSelect,
  MazSidebar,
  MazSlider,
  MazSpinner,
  MazStepper,
  MazSwitch,
  MazTabsBar,
  MazTabsContent,
  MazTabsContentItem,
  MazTransitionExpand
}

export {
  version,
  install
}
/* eslint-enable */
