module.exports = {
  'base-colors': {
    transparent: 'transparent',
    black: 'var(--maz-color-black)',
    'black-contrast': 'var(--maz-color-black-contrast)',
    white: 'var(--maz-color-white)',
    'white-contrast': 'var(--maz-color-white-contrast)',
    current: 'currentColor',
    'normal-text': 'var(--maz-color-normal-text)',
    color: 'var(--maz-color-bg)',
    'color-light': 'var(--maz-color-bg-light)',
    'color-lighter': 'var(--maz-color-bg-lighter)',
  },
  variations: [
    'DEFAULT',
    50,
    100,
    200,
    300,
    400,
    600,
    700,
    800,
    900,
    'contrast',
  ],
  'variating-colors': {
    primary: true,
    secondary: true,
    'accent-hover': ['DEFAULT'],
    info: true,
    success: true,
    warning: true,
    danger: true,
  },
}
