name: Builds

on:
  pull_request:
    paths:
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/linters.yml'

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: 'pnpm'

      - name: Print app version package.json
        run: cat ./packages/lib/package.json | grep version

      - name: Install dependencies
        run: pnpm install

      - name: Generate components docs
        run: pnpm --filter cli cli generate-components-docs

      - name: Build lib
        run: pnpm -r build

      - name: Cat docs generated docs
        run: cat ./packages/docs/docs/.vitepress/dist/components/maz-picker.html
