name: Build and Typecheck

on:
  pull_request:
    paths:
      - 'packages/**'
      - pnpm-lock.yaml
      - .github/workflows/typecheck.yml

jobs:
  build-and-typecheck:
    name: build-and-typecheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js, pnpm and Nx cache
        uses: ./.github/actions/setup

      - name: Build packages
        run: |
          pnpm build:packages
          pnpm -F @maz-ui/nuxt prepare

      - name: Generate components docs
        run: pnpm --filter cli cli generate-components-docs

      - name: Build docs
        run: pnpm -F docs build
