name: Builds

on:
  pull_request:
    paths:
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/linters.yml'

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate components docs
        run: pnpm --filter cli cli generate-components-docs

      - name: Build lib
        run: pnpm -r build
