name: Build Lib Tests
on:
  pull_request:
    branches: [master]
    paths:
      - "packages/lib/**"

jobs:
  build-lib-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install all dependencies
        run: make install
      - name: Build lib
        run: make build-lib
