name: Doc Build Test
on:
  pull_request:
    paths:
      - 'packages/docs/**'
      - 'packages/lib/**'
      - '.github/workflows/doc-build-test.yml'

jobs:
  doc-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: make install

      - name: Install and build docs
        run: make generate-components-docs build-docs
