name: Doc Build Test
on:
  pull_request:
    paths:
      - 'packages/docs/**'
      - 'packages/lib/**'

jobs:
  doc-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install and build lib
        run: make install-lib build-lib

      - name: Install cli
        run: make install-cli

      - name: Install and build docs
        run: make install-docs generate-components-docs build-docs
