name: Doc Build Test
on:
  pull_request:
    branches:
      - master
      - next
      - "release/**"
    paths:
      - "packages/docs/**"
      - "packages/lib/**"

jobs:
  doc-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install all dependencies
        run: make install-lib install-docs

      - name: Build lib
        run: make build-lib

      - name: Build docs
        run: make build-docs
