name: Unit Tests

on:
  pull_request:
    branches-ignore:
      - dependabot/**
    paths:
      - .github/workflows/lib-test-unit.yml
      - 'packages/**'
      - pnpm-lock.yaml
  push:
    branches:
      - master

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: Europe/Paris
          timezoneMacos: Europe/Paris

      - uses: actions/checkout@v3

      - name: Setup Node.js, pnpm and Nx cache
        uses: ./.github/actions/setup

      - name: Build utils
        run: pnpm build:utils

      - name: Run others tests
        run: pnpm test:unit:coverage:all

      - name: Test & Publish Code Coverage
        uses: qltysh/qlty-action/coverage@main
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ${{github.workspace}}/packages/lib/coverage/lcov.info
