name: Lib Publish To Npm

on:
  release:
    types: [created]

# on:
#   push:
#     tags:
#       - v*.*.*

jobs:
  lib-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm --filter maz-ui install

      - name: Build Lib
        run: pnpm --filter maz-ui build

      - run: cd dist && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
