name: Lib Test Build

on:
  pull_request:
    paths:
      - 'packages/lib/**'

jobs:
  lib-test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm --filter maz-ui install

      - name: Build lib
        run: pnpm --filter maz-ui build
