name: Lib Test Build
on:
  push:
    branches:
      - master
      - next
    paths:
      - "packages/lib/**"
  pull_request:
    branches:
      - master
      - next
      - "release/**"
    paths:
      - "packages/lib/**"

jobs:
  lib-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm i

      - name: Build lib
        run: make build-lib
