name: Lib Tests Unit

on:
  push:
    branches:
      - master
      - next
    paths:
      - "packages/lib/**"
  pull_request:
    branches:
      - master
      - next
      - "release/**"
    paths:
      - "packages/lib/**"

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Actions
        uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: "16"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install modules
        run: npm i

      - name: Test & Publish Code Coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-unit-coverage
          coverageLocations: |
            ${{github.workspace}}/packages/lib/coverage/clover.xml:clover
