name: Unit Tests

on:
  push:
    branches-ignore:
      - dependabot/**
    paths:
      - '.github/workflows/lib-test-unit.yml'
      - 'packages/lib/**'
      - 'pnpm-lock.yaml'

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: 'Europe/Paris'
          timezoneMacos: 'Europe/Paris'

      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'pnpm'

      - name: Install modules
        run: pnpm install --frozen-lockfile

      - name: Test & Publish Code Coverage
        uses: qltysh/qlty-action/coverage@main
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ${{github.workspace}}/packages/lib/coverage/lcov.info
