name: Tests Units

on:
  push:
    branches: [master, next]
  pull_request:
    branches: [master, next]

jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/lib

    steps:
      - name: Checkout Actions
        uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: "16"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install modules
        run: make install

      - name: Run tests unit coverage
        run: make test-unit-coverage

      - name: Cat 1
        run: cat ./coverage/clover.xml

      - name: Find and Replace Files Paths
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "/Users/mazel/workspace/maz-ui/packages"
          replace: "packages"
          include: ${{github.workspace}}/packages/lib/coverage/clover.xml

      - name: Cat 2
        run: cat ./coverage/clover.xml

      - name: Test & Publish Code Coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/packages/lib/coverage/clover.xml
