name: Lib Publish To Npm

on:
  release:
    types: [published]
  push:
    paths:
      - 'packages/lib/**'

jobs:
  lib-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '21'
          registry-url: 'https://registry.npmjs.org'

      - name: Get last repo version
        run: git pull origin master

      - name: Install dependencies
        run: pnpm install

      - name: Build Lib
        run: pnpm --filter maz-ui build

      - name: Publish package to npm registry
        run: cd packages/lib/dist && pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
