name: Lib Tests Unit (Dependabot)

on:
  pull_request:
    branches:
      - dependabot/**
    paths:
      - .github/workflows/lib-test-unit-dependabot.yml
      - 'packages/lib/**'
      - pnpm-lock.yaml

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: Europe/Paris
          timezoneMacos: Europe/Paris

      - uses: actions/checkout@v3

      - name: Build utils
        run: pnpm build:utils

      - name: Setup Node.js, pnpm and Nx cache
        uses: ./.github/actions/setup

      - name: Test units
        run: pnpm test:unit:all
