name: Release Latest

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-latest:
    name: Release Latest
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Setup Node.js, pnpm and Nx cache
        uses: ./.github/actions/setup
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Build Packages
        run: pnpm build:packages

      - name: Setup Git User
        run: |
          git config --global user.name "LouisMazel"
          git config --global user.email "me@louismazel.com"

      - name: Graduate Pre-release to Stable
        run: pnpm lerna:version:graduate
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Publish to NPM (Latest)
        run: pnpm lerna:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
