name: Build and Deploy
on:
  push:
    branches: [master]
    # paths:
    #   - "packages/docs/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install all dependencies
        run: make install
      - name: Build lib
        run: make build-lib
      - name: Build docs
        run: make build-docs

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: LouisMazel/maz-ui-3
          TARGET_BRANCH: gh-pages
          BUILD_DIR: packages/docs/docs/.vuepress/dist
